import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter/widgets.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:window_manager/window_manager.dart';

const String _prefsKey = 'window_state';
const Size _defaultSize = Size(1280, 800);
const Size _minimumSize = Size(640, 480);

bool get _isDesktop =>
    defaultTargetPlatform == TargetPlatform.windows ||
    defaultTargetPlatform == TargetPlatform.linux ||
    defaultTargetPlatform == TargetPlatform.macOS;

/// Restores the saved desktop window geometry (or applies sensible defaults)
/// and begins persisting future size, position, and maximized changes.
///
/// No-op on mobile — only desktop platforms have an OS window to manage.
/// Assumes `WidgetsFlutterBinding.ensureInitialized()` has already run.
///
/// Note on position: under Wayland the compositor owns window placement and
/// silently ignores client requests to move a window, so position is neither
/// meaningfully restorable nor savable there. Size and maximized state work on
/// all desktops; position additionally works on X11, macOS, and Windows.
Future<void> initWindowManager() async {
  if (!_isDesktop) return;

  await windowManager.ensureInitialized();
  final prefs = SharedPreferencesAsync();
  final saved = await _readSaved(prefs);

  final options = WindowOptions(
    size: saved?.size ?? _defaultSize,
    minimumSize: _minimumSize,
    center: saved == null,
    title: 'BrainFrame',
  );

  await windowManager.waitUntilReadyToShow(options, () async {
    // Size comes from WindowOptions; restore position separately (a no-op on
    // Wayland). Skip it when maximized — maximize() drives the geometry.
    if (saved?.position != null && !(saved!.isMaximized)) {
      await windowManager.setPosition(saved.position!);
    }
    await windowManager.show();
    await windowManager.focus();
    if (saved?.isMaximized ?? false) {
      await windowManager.maximize();
    }
  });

  await _applyWindowIcon();

  // Persist on close as well as on change, so the final geometry is never lost.
  await windowManager.setPreventClose(true);
  windowManager.addListener(_WindowStatePersister(prefs));
}

/// Sets the desktop window's title-bar icon to the bundled BrainFrame logo.
///
/// `windowManager.setIcon` takes a filesystem path, but the logo ships as a
/// Flutter asset, so extract it to a temp file first. Windows and Linux only —
/// macOS draws its window/dock icon from the app bundle (generated by
/// `flutter_launcher_icons`). The icon is cosmetic, so any failure is swallowed
/// rather than allowed to break startup.
Future<void> _applyWindowIcon() async {
  if (defaultTargetPlatform != TargetPlatform.windows &&
      defaultTargetPlatform != TargetPlatform.linux) {
    return;
  }
  try {
    final data = await rootBundle.load('brainframe.png');
    final iconFile =
        File('${Directory.systemTemp.path}/brainframe_window_icon.png');
    await iconFile.writeAsBytes(
      data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes),
    );
    await windowManager.setIcon(iconFile.path);
  } catch (_) {
    // The window icon is cosmetic; never let it break startup.
  }
}

/// Persists window geometry whenever it changes.
///
/// Linux (GTK) emits only the present-tense `resize`/`move` events, while
/// macOS and Windows emit the past-tense `resized`/`moved` variants. We listen
/// for both and debounce, since the present-tense events fire continuously
/// during a drag.
class _WindowStatePersister extends WindowListener {
  _WindowStatePersister(this._prefs);

  final SharedPreferencesAsync _prefs;
  Timer? _debounce;

  void _scheduleSave() {
    _debounce?.cancel();
    _debounce = Timer(const Duration(milliseconds: 400), _save);
  }

  Future<void> _save() async {
    final isMaximized = await windowManager.isMaximized();

    if (isMaximized) {
      // Keep the previously stored "normal" geometry so that un-maximizing on
      // next launch restores a sensible size rather than the full-screen one.
      final previous = await _readSaved(_prefs);
      await _write(
        position: previous?.position,
        size: previous?.size ?? _defaultSize,
        isMaximized: true,
      );
      return;
    }

    await _write(
      position: await windowManager.getPosition(),
      size: await windowManager.getSize(),
      isMaximized: false,
    );
  }

  Future<void> _write({
    required Offset? position,
    required Size size,
    required bool isMaximized,
  }) async {
    await _prefs.setString(
      _prefsKey,
      jsonEncode({
        if (position != null) 'x': position.dx,
        if (position != null) 'y': position.dy,
        'width': size.width,
        'height': size.height,
        'maximized': isMaximized,
      }),
    );
  }

  // Present-tense (Linux) and past-tense (macOS/Windows) geometry events.
  @override
  void onWindowResize() => _scheduleSave();

  @override
  void onWindowResized() => _scheduleSave();

  @override
  void onWindowMove() => _scheduleSave();

  @override
  void onWindowMoved() => _scheduleSave();

  @override
  void onWindowMaximize() => _scheduleSave();

  @override
  void onWindowUnmaximize() => _scheduleSave();

  @override
  Future<void> onWindowClose() async {
    _debounce?.cancel();
    try {
      await _save();
    } finally {
      // We intercepted the close (setPreventClose); always actually close,
      // even if the final save failed.
      await windowManager.destroy();
    }
  }
}

class _SavedWindowState {
  const _SavedWindowState({
    required this.position,
    required this.size,
    required this.isMaximized,
  });

  /// Null when no position was stored (e.g. saved under Wayland).
  final Offset? position;
  final Size size;
  final bool isMaximized;
}

Future<_SavedWindowState?> _readSaved(SharedPreferencesAsync prefs) async {
  final raw = await prefs.getString(_prefsKey);
  if (raw == null) return null;
  try {
    final map = jsonDecode(raw) as Map<String, dynamic>;
    final x = map['x'] as num?;
    final y = map['y'] as num?;
    return _SavedWindowState(
      position: (x != null && y != null)
          ? Offset(x.toDouble(), y.toDouble())
          : null,
      size: Size(
        (map['width'] as num).toDouble(),
        (map['height'] as num).toDouble(),
      ),
      isMaximized: map['maximized'] as bool? ?? false,
    );
  } catch (_) {
    // Corrupt or outdated state — fall back to defaults.
    return null;
  }
}
